apiVersion: tenant.my.domain/v1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: tenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: tenant-sample
spec:
  # TODO(user): Add fields here
